; Sentaurus Training BVmethods NMOS structure (Workbench node 1).
; Length unit: um. Doping unit: cm^-3.

(sde:clear)
(sde:set-process-up-direction +z)

(define Lg 0.13)
(define Lsp 0.1)
(define Lreox 0.01)
(define Ltot (+ Lg (* 2 Lsp) 0.8))
(define Hsub 1.0)
(define Tox 0.002)
(define Hpol 0.2)
(define fillet-radius 0.08)
(define Gpn 0.008)
(define SubDop 1e18)
(define Xj 0.1)

(define Xmax (/ Ltot 2.0))
(define Xg (/ Lg 2.0))
(define Xsp (+ Xg Lsp))
(define Ysub Hsub)
(define Ygox (* Tox -1.0))
(define Ypol (- Ygox Hpol))
(define Lcont (- Xmax Xsp))

(sdegeo:set-default-boolean "ABA")
(sdegeo:create-rectangle (position 0.0 Ysub 0.0) (position Xmax 0.0 0.0) "Silicon" "R.Substrate")
(sdegeo:create-rectangle (position 0.0 0.0 0.0) (position Xsp Ygox 0.0) "Oxide" "R.Gateox")
(sdegeo:create-rectangle (position 0.0 Ygox 0.0) (position Xsp Ypol 0.0) "Oxide" "R.PolyReox")
(sdegeo:create-rectangle (position (+ Xg Lreox) Ygox 0.0) (position Xsp Ypol 0.0) "Nitride" "R.Spacer")
(sdegeo:create-rectangle (position 0.0 Ygox 0.0) (position Xg Ypol 0.0) "PolySi" "R.Polygate")
(sdegeo:fillet-2d (find-vertex-id (position Xsp Ypol 0.0)) fillet-radius)

(sdegeo:set-contact (find-edge-id (position (* (+ Xmax Xsp) 0.5) 0.0 0.0)) "drain")
(sdegeo:set-contact (find-body-id (position 0.0005 -0.1 0.0)) "gate" "remove")
(sdegeo:set-contact (find-edge-id (position 0.0005 Ysub 0.0)) "substrate")

(sdedr:define-constant-profile "Const.Substrate" "BoronActiveConcentration" SubDop)
(sdedr:define-constant-profile-region "PlaceCD.Substrate" "Const.Substrate" "R.Substrate")
(sdedr:define-constant-profile "Const.Gate" "ArsenicActiveConcentration" 1e20)
(sdedr:define-constant-profile-region "PlaceCD.Gate" "Const.Gate" "R.Polygate")

(sdedr:define-refeval-window "BaseLine.Drain" "Line" (position Xsp 0.0 0.0) (position (* Xmax 2.0) 0.0 0.0))
(sdedr:define-gaussian-profile "Impl.SDprof" "ArsenicActiveConcentration" "PeakPos" 0 "PeakVal" 5e20 "ValueAtDepth" SubDop "Depth" Xj "Erf" "Factor" 0.4)
(sdedr:define-analytical-profile-placement "Impl.Drain" "Impl.SDprof" "BaseLine.Drain" "Symm" "NoReplace" "Eval")
(sdedr:define-refeval-window "BaseLine.DrainExt" "Line" (position Xg 0.0 0.0) (position (* Xmax 2.0) 0.0 0.0))
(sdedr:define-gaussian-profile "Impl.SDextprof" "ArsenicActiveConcentration" "PeakPos" 0 "PeakVal" 1e19 "ValueAtDepth" SubDop "Depth" (* Xj 0.5) "Erf" "Factor" 0.8)
(sdedr:define-analytical-profile-placement "Impl.DrainExt" "Impl.SDextprof" "BaseLine.DrainExt" "Symm" "NoReplace" "Eval")

(sdedr:define-refinement-size "Ref.Substrate" (/ Ltot 4.0) (/ Hsub 8.0) Gpn Gpn)
(sdedr:define-refinement-function "Ref.Substrate" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-refinement-region "RefPlace.Substrate" "Ref.Substrate" "R.Substrate")
(sdedr:define-refeval-window "RWin.Act" "Rectangle" (position 0.0 0.0 0.0) (position Xmax (* Xj 1.8) 0.0))
(sdedr:define-refinement-size "Ref.SiAct" (/ Lcont 4.0) (/ Xj 4.0) Gpn Gpn)
(sdedr:define-refinement-function "Ref.SiAct" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-refinement-placement "RefPlace.SiAct" "Ref.SiAct" "RWin.Act")
(sdedr:define-refinement-size "Ref.GOX" (/ Ltot 4.0) (/ Tox 4.0) Gpn (/ Tox 8.0))
(sdedr:define-refinement-region "RefPlace.GOX" "Ref.GOX" "R.Gateox")

(sdedr:define-refeval-window "MBWindow.Gate" "Rectangle" (position 0.0 Ypol 0.0) (position Xg Ygox 0.0))
(sdedr:define-multibox-size "MBSize.Gate" (/ Lg 6.0) (/ Hpol 8.0) (/ Lg 8.0) 0.0003 1.0 -1.35)
(sdedr:define-multibox-placement "MBPlace.Gate" "MBSize.Gate" "MBWindow.Gate")
(sdedr:define-refeval-window "MBWindow.Channel" "Rectangle" (position 0.0 0.0 0.0) (position (* Xg 2.0) (* 1.2 Xj) 0.0))
(sdedr:define-multibox-size "MBSize.Channel" (/ Lg 6.0) (/ Xj 8.0) (/ Lg 8.0) 0.0002 1.0 1.35)
(sdedr:define-multibox-placement "MBPlace.Channel" "MBSize.Channel" "MBWindow.Channel")

(sdedr:define-refinement-size "Ref.J" (/ Lg 6.0) (/ Lg 6.0) Gpn Gpn)
(sdedr:define-refinement-function "Ref.J" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-refeval-window "RWin.GD" "Rectangle" (position (- Xg 0.01) 0.0 0.0) (position (* 1.2 Xsp) (* Xj 0.6) 0.0))
(sdedr:define-refinement-placement "RefPlace.GJ" "Ref.J" "RWin.GD")
(sdedr:define-refinement-size "Ref.JBV" (* 1.0 Gpn) (* 1.0 Gpn) (* 0.25 Gpn) (* 0.25 Gpn))
(sdedr:define-refinement-function "Ref.JBV" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-refeval-window "RWin.GDBV" "Rectangle" (position (- Xg 0.015) 0.0 0.0) (position (+ Xg 0.01) (* Xj 0.4) 0.0))
(sdedr:define-refinement-placement "RefPlace.GJBV" "Ref.JBV" "RWin.GDBV")

(sde:build-mesh "bvmethods_nmos_half_msh")
(system:command "tdx -mtt -x -M 0 -S 0 -ren drain=source bvmethods_nmos_half_msh bvmethods_nmos_msh")
